name: Generate Snake Animation

on:
  # 每天自动运行
  schedule:
    - cron: "0 0 * * *"
  # 允许手动运行 workflow
  workflow_dispatch:
  # 修改 main 分支时也会运行
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: suny1798
          outputs: |
            ./profile-snake-contrib/github-contribution-grid-snake.svg
            ./profile-snake-contrib/github-contribution-grid-snake-dark.svg

      - name: Commit and Push generated files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate snake animation"
          add: "profile-snake-contrib/"
